<a href="https://colab.research.google.com/github/shreyaghora/ArrhythmiaHub/blob/main/Code/Smote_Wilcoxon_Signed_Rank_Test_results.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install lightgbm
!pip install catboost
!pip install xgboost
!pip install specificity
!pip install imbalanced-learn
!pip install lime
!pip install xlsxwriter

!pip install ipython-autotime
%load_ext autotime

Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm) (1.16.3)
Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.9 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.27.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)
Collecting specificity
  Downloading specificity-1.0-py3-none-any.whl.metadata (159 bytes)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from specificity) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->specificity) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->specificity) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->specificity) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->specificity) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->specificity) (1.17.0)
Downloading specificity-1.0-py3-none-any.whl (3.2 kB)
Installing collected packages: specificity
Successfully installed specificity-1.0
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.12/dist-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (2.0.2)
Requirement already satisfied: scipy<2,>=1.11.4 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from imbalanced-learn) (3.6.0)
Collecting lime
  Downloading lime-0.2.0.1.tar.gz (275 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 10.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from lime) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from lime) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lime) (1.16.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from lime) (4.67.3)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.12/dist-packages (from lime) (1.6.1)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.12/dist-packages (from lime) (0.25.2)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (3.6.1)
Requirement already satisfied: pillow>=10.1 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (11.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (2.37.3)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (2026.4.11)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (26.1)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (0.5)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.18->lime) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.18->lime) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->lime) (1.17.0)
Building wheels for collected packages: lime
  Building wheel for lime (setup.py) ... done
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283834 sha256=9f0df531d681964f52a145fd3f8be094ff5e62fbc50943baede21a7adca9be84
  Stored in directory: /root/.cache/pip/wheels/e7/5d/0e/4b4fff9a47468fed5633211fb3b76d1db43fe806a17fb7486a
Successfully built lime
Installing collected packages: lime
Successfully installed lime-0.2.0.1
Collecting xlsxwriter
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Downloading xlsxwriter-3.2.9-py3-none-any.whl (175 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 7.6 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.9
Collecting ipython-autotime
  Downloading ipython_autotime-0.3.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipython-autotime) (7.34.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (75.2.0)
Collecting jedi>=0.16 (from ipython->ipython-autotime)
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-autotime) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipython-autotime) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipython-autotime) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->ipython-autotime) (0.6.0)
Downloading ipython_autotime-0.3.2-py2.py3-none-any.whl (7.0 kB)
Downloading jedi-0.20.0-py2.py3-none-any.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 62.2 MB/s eta 0:00:00
Installing collected packages: jedi, ipython-autotime
Successfully installed ipython-autotime-0.3.2 jedi-0.20.0
time: 342 µs (started: 2026-05-19 08:03:24 +00:00)

In [ ]:
import numpy as np
import pandas as pd
import time
import shap
import matplotlib.pyplot as plt

from scipy.stats import uniform
from lime.lime_tabular import LimeTabularExplainer

from sklearn.model_selection import train_test_split, KFold, RandomizedSearchCV, cross_validate
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, BaggingClassifier, StackingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV, cross_validate

from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, matthews_corrcoef, cohen_kappa_score, confusion_matrix, balanced_accuracy_score

time: 9.75 s (started: 2026-05-19 08:21:53 +00:00)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
time: 25 s (started: 2026-05-19 08:22:30 +00:00)

In [ ]:
df = pd.read_csv("INCART 2-lead Arrhythmia Database.csv")
df.head(50)

,record,type,0_pre-RR,0_post-RR,0_pPeak,0_tPeak,0_rPeak,0_sPeak,0_qPeak,0_qrs_interval,...,1_qPeak,1_qrs_interval,1_pq_interval,1_qt_interval,1_st_interval,1_qrs_morph0,1_qrs_morph1,1_qrs_morph2,1_qrs_morph3,1_qrs_morph4
0,I01,N,163,165,0.069610,-0.083281,0.614133,-0.392761,0.047159,15,...,-0.023370,14,3,23,6,-0.023370,-0.011650,0.082608,0.101373,-0.183387
1,I01,N,165,166,-0.097030,0.597254,-0.078704,-0.078704,-0.137781,3,...,0.081637,15,5,27,7,0.081637,0.102992,0.191225,0.217544,-0.068248
2,I01,N,166,102,0.109399,0.680528,-0.010649,-0.010649,-0.720620,6,...,-0.148539,33,13,52,6,-0.148539,-0.060620,0.081080,0.204400,0.335172
3,I01,VEB,102,231,0.176376,0.256431,-0.101098,-0.707525,-0.101098,4,...,0.046898,21,9,34,4,0.046898,0.083728,0.279512,0.526785,0.450969
4,I01,N,231,165,0.585577,0.607461,-0.083499,-0.083499,-0.167858,3,...,-0.112552,32,5,43,6,-0.112552,0.012989,0.091491,0.134004,0.265232
5,I01,N,165,163,0.019637,-0.111671,0.613374,-0.416937,-0.108554,21,...,-0.088215,32,8,47,7,-0.088215,-0.001563,0.082968,0.136342,0.308107
6,I01,N,163,166,-0.156761,0.528148,-0.145137,-0.145137,-0.183749,2,...,0.066682,16,5,27,6,0.066682,0.084804,0.174772,0.224360,-0.011853
7,I01,N,166,161,-0.003887,0.216949,1.120258,0.164411,-0.725340,33,...,-0.198099,3,4,14,7,-0.198099,-0.198099,-0.322683,-0.322683,-0.429821
8,I01,N,161,160,-0.006721,0.164998,0.601190,-0.307812,-0.035103,15,...,0.062813,14,9,29,6,0.062813,0.080551,0.159296,0.108512,-0.248600
9,I01,N,160,158,-0.187870,0.544414,-0.018564,-0.018564,-0.194883,5,...,0.127967,14,5,26,7,0.127967,0.147617,0.247298,0.264875,-0.032502
10,I01,N,158,162,-0.040585,0.635823,-0.053904,-0.053904,-0.063889,1,...,0.052169,16,2,25,7,0.052169,0.076442,0.178419,0.281661,0.143901
11,I01,N,162,161,-0.081198,0.623240,-0.062096,-0.062096,-0.123958,2,...,0.096507,15,3,25,7,0.096507,0.116449,0.214933,0.231600,-0.067133
12,I01,N,161,156,0.086558,0.393499,0.719685,-0.250740,-0.538251,20,...,-0.164989,32,13,51,6,-0.164989,-0.052172,0.070760,0.179198,0.304884
13,I01,N,156,164,-0.205547,0.638658,-0.164207,-0.164207,-0.214457,3,...,0.089653,13,5,24,6,0.089653,0.110915,0.187699,0.165968,-0.139647
14,I01,N,164,99,0.016927,-0.047951,0.756064,-0.356411,0.004137,15,...,0.016777,17,6,28,5,0.016777,0.047710,0.166775,0.283237,0.055741
15,I01,VEB,99,229,0.009672,0.202892,-0.337828,-0.812391,-0.337828,4,...,0.109772,35,2,65,28,0.109772,0.277229,0.638235,0.112592,-0.052973
16,I01,N,229,157,-0.077866,0.109204,0.845887,0.090167,-0.133799,16,...,-0.041888,4,3,14,7,-0.041888,-0.041888,-0.175961,-0.312023,-0.419915
17,I01,N,157,161,-0.000555,0.782663,-0.069553,-0.069553,-0.138956,2,...,-0.128642,33,5,44,6,-0.128642,-0.026086,0.081768,0.086364,0.253342
18,I01,N,161,160,-0.105416,-0.013756,0.609126,-0.511510,-0.172152,15,...,0.078856,15,6,27,6,0.078856,0.110051,0.200273,0.157872,-0.180717
19,I01,N,160,158,0.117002,0.799993,-0.211276,-0.211276,-0.790367,9,...,0.258240,13,3,21,5,0.258240,0.280209,0.333661,0.242610,-0.178878
20,I01,N,158,160,-0.104322,0.040906,0.757412,-0.357175,-0.185547,24,...,0.073693,19,3,29,7,0.073693,0.079184,0.104694,0.199935,0.032928
21,I01,N,160,158,0.453999,-0.118156,1.191751,-0.467899,0.431475,17,...,-0.147341,4,4,14,6,-0.147341,-0.147341,-0.257536,-0.360186,-0.426599
22,I01,N,158,159,0.037875,0.012596,0.784757,-0.249680,-0.023527,17,...,0.124920,13,10,29,6,0.124920,0.147599,0.196232,0.140291,-0.219807
23,I01,N,159,159,-0.096663,-0.211204,0.608971,-0.580764,-0.174658,16,...,0.109796,15,4,26,7,0.109796,0.136428,0.234228,0.260969,-0.010044
24,I01,N,159,162,0.269521,-0.079315,0.734648,-0.355954,-0.043137,16,...,-0.178392,33,22,61,6,-0.178392,-0.046576,0.028500,0.069354,0.196874
25,I01,N,162,165,-0.179603,0.590867,-0.127932,-0.127932,-0.210318,3,...,0.111269,14,6,27,7,0.111269,0.123292,0.212181,0.235793,-0.055824
26,I01,N,165,167,-0.039205,-0.072344,0.693283,-0.410708,-0.049118,16,...,-0.163343,33,23,63,7,-0.163343,-0.042005,0.070189,0.087386,0.244986
27,I01,N,167,168,-0.075328,-0.067987,0.633289,-0.360871,-0.103375,17,...,0.064171,15,5,26,6,0.064171,0.094606,0.194686,0.173850,-0.155923
28,I01,N,168,167,-0.065332,-0.017786,0.582341,-0.288825,-0.068888,17,...,0.076933,16,4,26,6,0.076933,0.096405,0.188398,0.226638,-0.017164
29,I01,N,167,170,-0.106524,0.670969,-0.088034,-0.088034,-0.124556,2,...,0.062070,17,3,26,6,0.062070,0.089997,0.172312,0.273631,0.017892
30,I01,N,170,107,-0.069407,-0.094781,0.605720,-0.331625,-0.094995,15,...,0.075741,13,5,25,7,0.075741,0.105752,0.217744,0.214103,-0.074785
31,I01,VEB,107,239,0.304862,0.285580,-0.002046,-0.715299,-0.002046,4,...,0.017242,21,11,33,1,0.017242,0.067571,0.287925,0.539990,0.336919
32,I01,N,239,169,0.207640,0.021081,0.432413,-0.466604,-0.182300,15,...,-0.216721,32,13,51,6,-0.216721,-0.088081,0.047687,0.088800,0.238781
33,I01,N,169,168,-0.161107,0.531544,-0.163141,-0.163141,-0.253817,2,...,0.068664,21,2,29,6,0.068664,0.129685,0.197834,0.283694,0.179276
34,I01,N,168,171,-0.183925,0.631625,-0.183045,-0.183045,-0.197283,1,...,0.080806,13,2,21,6,0.080806,0.105796,0.237062,0.195440,-0.216577
35,I01,N,171,164,-0.069845,0.006591,0.844474,-0.305859,-0.090416,16,...,0.058068,14,5,25,6,0.058068,0.076237,0.161892,0.201273,-0.045120
36,I01,N,164,166,0.121666,-0.046190,0.762414,-0.327565,0.006480,16,...,0.033363,14,3,24,7,0.033363,0.051665,0.165401,0.179927,-0.097213
37,I01,N,166,165,0.078861,-0.116395,0.685158,-0.353521,0.000217,15,...,-0.025655,17,7,30,6,-0.025655,0.058747,0.141948,0.174367,-0.028643
38,I01,N,165,164,0.309135,-0.046069,0.786521,-0.425424,0.004173,16,...,-0.003381,16,5,27,6,-0.003381,0.036859,0.164048,0.226586,-0.057804
39,I01,N,164,166,0.240490,0.716878,-0.113359,-0.113359,-0.121076,1,...,0.058927,15,4,25,6,0.058927,0.106329,0.212442,0.194119,-0.126952
40,I01,N,166,162,0.195630,0.036849,0.809041,-0.308981,-0.274450,23,...,0.136096,17,4,27,6,0.136096,0.155928,0.188126,0.185806,-0.070465
41,I01,N,162,162,-0.016362,-0.034908,0.658946,-0.280717,-0.054973,16,...,0.063269,17,6,29,6,0.063269,0.073873,0.136410,0.229475,0.006535
42,I01,N,162,161,0.044359,0.613769,-0.032353,-0.032353,-0.032353,0,...,0.044076,13,4,24,7,0.044076,0.103073,0.242952,0.225111,-0.100355
43,I01,N,161,162,-0.105582,0.804256,-0.071827,-0.071827,-0.134623,3,...,0.078782,15,5,26,6,0.078782,0.129190,0.231032,0.188412,-0.159986
44,I01,N,162,163,0.030395,0.484071,-0.106689,-0.106689,-0.132685,1,...,0.033483,14,4,24,6,0.033483,0.064054,0.199058,0.200863,-0.091926
45,I01,N,163,162,-0.119633,0.569694,-0.019918,-0.019918,-0.136312,3,...,0.061752,18,1,26,7,0.061752,0.073930,0.139172,0.244426,0.113284
46,I01,N,162,160,0.213081,-0.125926,0.530420,-0.568793,-0.218720,15,...,0.064454,14,5,25,6,0.064454,0.100001,0.215403,0.235369,-0.020062
47,I01,N,160,157,0.081675,-0.020076,0.716604,-0.281617,0.009859,15,...,0.031019,14,3,23,6,0.031019,0.046744,0.124237,0.133813,-0.136605
48,I01,N,157,158,0.156457,-0.006803,0.895511,-0.356822,-0.198248,28,...,0.027714,2,9,13,2,0.027714,0.027714,0.027714,0.021152,0.021152
49,I01,N,158,161,-0.043381,0.732018,-0.026879,-0.026879,-0.326714,12,...,0.091107,14,7,27,6,0.091107,0.108783,0.187637,0.208348,-0.066192

time: 1.25 s (started: 2026-05-19 08:22:58 +00:00)

In [ ]:
# # 3. Drop Feature
df.drop('record', axis=1, inplace=True)

df = df[df['type'] != 'Q']

# 5. Encode Target
df['type'] = df['type'].map({'F': 0, 'N': 1, 'SVEB': 2, 'VEB': 3});
X = df.drop('type', axis=1)
y = df['type']

feature_names = X.columns;

# 9. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 8. Apply SMOTE
sm = SMOTE(random_state=42, k_neighbors=2)
X_train_sm, y_train_sm = sm.fit_resample(X_train, y_train)

# 8. SCALE DATA
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train_sm)
X_test_scaled = scaler.transform(X_test)

time: 2.49 s (started: 2026-05-19 08:23:00 +00:00)

In [ ]:
def hyper_parameter_tune(model, param_dist, X_train, y_train):

    search = RandomizedSearchCV(
          model,
          param_distributions=param_dist,
          n_iter=5,
          cv=5,
          refit='roc_auc',
          n_jobs=-1,
          random_state=42,
          return_train_score=False
          )

    search.fit(X_train, y_train)

    best_model = search.best_estimator_

    print("Best parameters:", search.best_params_)
    print("Best CV accuracy: {:.4f}".format(search.best_score_))


    return best_model

time: 658 µs (started: 2026-05-19 08:23:02 +00:00)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
    matthews_corrcoef,
    cohen_kappa_score,
    balanced_accuracy_score
)

from sklearn.model_selection import KFold
from sklearn.preprocessing import label_binarize

import numpy as np
import pandas as pd
import time


def evaluate_models(name, model, X, y):

    result = []

    print(f"\nTrain Model: {name}\n")

    kf = KFold(n_splits=10, shuffle=True, random_state=42)

    classes = np.unique(y)

    for fold, (train_idx, test_idx) in enumerate(kf.split(X)):

        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        # Train
        start_time = time.time()

        model.fit(X_train, y_train)

        training_time = time.time() - start_time

        # Predict
        y_pred = model.predict(X_test)

        # Metrics
        acc = accuracy_score(y_test, y_pred)

        prec = precision_score(y_test,y_pred,average='weighted',zero_division=0)

        rec = recall_score(y_test,y_pred,average='weighted',zero_division=0)

        f1 = f1_score(y_test,y_pred,average='weighted',zero_division=0)

        balanced_acc = balanced_accuracy_score(y_test, y_pred)

        mcc = matthews_corrcoef(y_test, y_pred)

        kappa = cohen_kappa_score(y_test, y_pred)

        try:
            y_prob = model.predict_proba(X_test)

            y_test_bin = label_binarize(y_test, classes=classes)

            auc = roc_auc_score(
                y_test_bin,
                y_prob,
                multi_class='ovr'
            )

        except:
            auc = np.nan

        result.append({
            "Classifier": name,
            "Fold": fold + 1,
            "Accuracy": acc,
            "Precision": prec,
            "Recall": rec,
            "F1": f1,
            "AUC": auc,
            "MCC": mcc,
            "Kappa": kappa,
            "Balanced Accuracy": balanced_acc,
            "Training Time (s)": training_time
        })

    return pd.DataFrame(result)

time: 2.24 ms (started: 2026-05-19 08:23:04 +00:00)

In [ ]:
#  SHAP EXPLAINABILITY
def shap_explain(model, explainer_type, X_test_scaled, feature_names, X_test = X_test):
  print("\n--- SHAP EXPLANATION ---")


  # Use TreeExplainer (since RandomForest is tree-based)
  explainer = explainer_type(model)

  # Compute SHAP values
  shap_values = explainer.shap_values(X_test_scaled)

  # -------------------------------
  # 1. GLOBAL FEATURE IMPORTANCE
  # -------------------------------
  plt.figure()
  shap.summary_plot(shap_values, X_test_scaled, feature_names=feature_names, plot_type="bar")

  # -------------------------------
  # 2. DETAILED SUMMARY PLOT
  # -------------------------------
  plt.figure()

  shap.summary_plot(shap_values, X_test_scaled, feature_names=feature_names)
  plt.figure()

  # # -------------------------------
  # # 3. DEPENDENCE PLOT
  # # -------------------------------
  # # Change feature name as needed
  # shap.dependence_plot(
  #     feature_names[0],  # example feature
  #     shap_values,
  #     X_test_scaled,
  #     feature_names=feature_names # Provide feature names for clarity
  # )

  # # -------------------------------
  # # 4. LOCAL EXPLANATION (FORCE PLOT)
  # # -------------------------------
  # # Use expected value of class 1
  # expected_value = explainer.expected_value

  # plt.figure()
  # shap.force_plot(
  #     expected_value,
  #     shap_values[0], # shap_vals is now (num_samples, num_features), so shap_vals[0] is for the first sample
  #     X_test.iloc[0],
  #     matplotlib=True
  # )

time: 945 µs (started: 2026-05-19 08:23:08 +00:00)

In [ ]:
# LIME EXPLAINABILITY

def lime_explain(model, X_train_scaled, X_test_scaled, feature_names, num_samples=100):

    print("\n--- LIME EXPLANATION ---")

    from lime.lime_tabular import LimeTabularExplainer
    import numpy as np
    import pandas as pd

    X_train_np = X_train_scaled.to_numpy() if hasattr(X_train_scaled, "to_numpy") else X_train_scaled
    X_test_np = X_test_scaled.to_numpy() if hasattr(X_test_scaled, "to_numpy") else X_test_scaled


    lime_explainer = LimeTabularExplainer(
        training_data=X_train_np,
        feature_names=feature_names,
        class_names=model.classes_.astype(str) if hasattr(model, "classes_") else None,
        mode='classification'
    )


    # 1. LOCAL EXPLANATION

    print("\n--- LOCAL EXPLANATION ---")

    lime_exp = lime_explainer.explain_instance(
        X_test_np[0],
        model.predict_proba
    )

    lime_exp.show_in_notebook(show_table=True)

    # 2. GLOBAL EXPLANATION

    print("\n--- GLOBAL EXPLANATION (approx via sampling) ---")

    feature_importance = np.zeros(X_train_np.shape[1])


    indices = np.random.choice(len(X_test_np), min(num_samples, len(X_test_np)), replace=False)

    for i in indices:
        exp = lime_explainer.explain_instance(
            X_test_np[i],
            model.predict_proba,
            num_features=len(feature_names)
        )

        for feature, weight in exp.as_list():

            feature_index = next(
                (j for j, name in enumerate(feature_names) if name in feature),
                None
            )

            if feature_index is not None:
                feature_importance[feature_index] += abs(weight)

    # Normalize importance
    feature_importance /= len(indices)

    # Create dataframe
    global_lime = pd.DataFrame({
        "feature": feature_names,
        "importance": feature_importance
    }).sort_values(by="importance", ascending=False)

    print(global_lime)

time: 4.14 ms (started: 2026-05-19 08:23:11 +00:00)

In [ ]:
from sklearn.neural_network import MLPClassifier

name="MLP"

#Model
model =   MLPClassifier(max_iter=300)
param_dist = {
      "hidden_layer_sizes": [(64,64), (128,64)]
}

best_model = hyper_parameter_tune(model, param_dist, X_train_scaled, y_train_sm)

MLP = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
MLP

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 2 is smaller than n_iter=5. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Best parameters: {'hidden_layer_sizes': (128, 64)}
Best CV accuracy: 0.9989

Train Model: MLP

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,MLP,1,0.999349,0.999349,0.999349,0.999348,0.999953,0.999131,0.999131,0.999347,351.834801
1,MLP,2,0.998941,0.998942,0.998941,0.998941,0.999968,0.998589,0.998588,0.998939,403.945937
2,MLP,3,0.998269,0.998272,0.998269,0.998269,0.999913,0.997694,0.997693,0.998279,582.365937
3,MLP,4,0.997944,0.997952,0.997944,0.997944,0.999955,0.997261,0.997258,0.997950,442.710343
4,MLP,5,0.999226,0.999227,0.999226,0.999226,0.999947,0.998969,0.998968,0.999222,368.395176
5,MLP,6,0.998921,0.998921,0.998921,0.998921,0.999960,0.998561,0.998561,0.998916,443.672083
6,MLP,7,0.999104,0.999105,0.999104,0.999104,0.999937,0.998806,0.998806,0.999108,329.817914
7,MLP,8,0.999491,0.999491,0.999491,0.999491,0.999967,0.999321,0.999321,0.999487,379.938530
8,MLP,9,0.999328,0.999328,0.999328,0.999328,0.999983,0.999104,0.999104,0.999331,352.115982
9,MLP,10,0.998371,0.998373,0.998371,0.998371,0.999976,0.997829,0.997828,0.998375,313.163197

time: 1h 44min 4s (started: 2026-05-16 22:07:16 +00:00)

time: 1h 44min 4s (started: 2026-05-16 22:07:16 +00:00)

time: 1h 44min 4s (started: 2026-05-16 22:07:16 +00:00)

In [ ]:
from xgboost import XGBClassifier

name ="XGBoost"

#Model
model =  XGBClassifier(use_label_encoder=False, eval_metric='logloss')

param_dist = {
    "n_estimators": [100, 200],
    "learning_rate": [0.01, 0.1],
            "max_depth": [3, 6]
}
best_model = hyper_parameter_tune(model, param_dist, X_train_scaled, y_train_sm)

XGBoost = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
XGBoost

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:03:34] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

Best parameters: {'n_estimators': 200, 'max_depth': 6, 'learning_rate': 0.1}
Best CV accuracy: 0.9988

Train Model: XGBoost

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:04:30] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:05:25] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:06:20] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:07:15] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:08:08] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:09:02] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:09:56] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:10:50] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:11:45] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [00:12:40] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,XGBoost,1,0.998717,0.998719,0.998717,0.998717,0.999969,0.998291,0.998290,0.998713,53.321095
1,XGBoost,2,0.998901,0.998901,0.998901,0.998900,0.999973,0.998535,0.998534,0.998898,53.340144
2,XGBoost,3,0.998962,0.998962,0.998962,0.998961,0.999960,0.998616,0.998616,0.998968,53.106362
3,XGBoost,4,0.998840,0.998840,0.998840,0.998839,0.999978,0.998453,0.998453,0.998845,50.341409
4,XGBoost,5,0.998840,0.998840,0.998840,0.998839,0.999970,0.998453,0.998453,0.998834,52.192216
5,XGBoost,6,0.998717,0.998718,0.998717,0.998717,0.999986,0.998290,0.998290,0.998710,53.038486
6,XGBoost,7,0.998534,0.998536,0.998534,0.998534,0.999972,0.998046,0.998045,0.998541,52.850798
7,XGBoost,8,0.998982,0.998982,0.998982,0.998982,0.999990,0.998643,0.998643,0.998974,53.357474
8,XGBoost,9,0.999063,0.999064,0.999063,0.999063,0.999990,0.998752,0.998751,0.999067,53.352210
9,XGBoost,10,0.999226,0.999226,0.999226,0.999226,0.999992,0.998969,0.998968,0.999227,51.083619

time: 22min 10s (started: 2026-05-16 23:51:21 +00:00)

time: 22min 10s (started: 2026-05-16 23:51:21 +00:00)

time: 22min 10s (started: 2026-05-16 23:51:21 +00:00)

In [ ]:
from sklearn.tree import DecisionTreeClassifier


name="DecisionTree"

#Model
model = DecisionTreeClassifier()

# Search space
param_dist = {

    "max_depth":[5,10,20,None],
    "min_samples_split":[2,5,10],
    "min_samples_leaf":[1,2,4]
}

best_model = hyper_parameter_tune(model, param_dist, X_train_scaled, y_train_sm)

DecisionTree = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
DecisionTree

Best parameters: {'min_samples_split': 2, 'min_samples_leaf': 2, 'max_depth': None}
Best CV accuracy: 0.9958

Train Model: DecisionTree

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,DecisionTree,1,0.995093,0.995090,0.995093,0.995090,0.997642,0.993459,0.993458,0.995082,50.872642
1,DecisionTree,2,0.996254,0.996254,0.996254,0.996253,0.998207,0.995006,0.995005,0.996250,48.959619
2,DecisionTree,3,0.996254,0.996253,0.996254,0.996253,0.998354,0.995006,0.995005,0.996265,50.765121
3,DecisionTree,4,0.995582,0.995582,0.995582,0.995581,0.998009,0.994110,0.994109,0.995591,49.411748
4,DecisionTree,5,0.996111,0.996111,0.996111,0.996110,0.998194,0.994816,0.994815,0.996102,50.692788
5,DecisionTree,6,0.996050,0.996049,0.996050,0.996049,0.998193,0.994734,0.994734,0.996048,50.443776
6,DecisionTree,7,0.996010,0.996008,0.996010,0.996008,0.998017,0.994680,0.994679,0.996026,50.064588
7,DecisionTree,8,0.996172,0.996172,0.996172,0.996172,0.998133,0.994897,0.994896,0.996158,50.778782
8,DecisionTree,9,0.995623,0.995622,0.995623,0.995622,0.997926,0.994164,0.994164,0.995630,49.824689
9,DecisionTree,10,0.996641,0.996641,0.996641,0.996640,0.998359,0.995522,0.995521,0.996639,49.678005

time: 19min 4s (started: 2026-05-17 00:13:32 +00:00)

time: 19min 4s (started: 2026-05-17 00:13:32 +00:00)

time: 19min 4s (started: 2026-05-17 00:13:32 +00:00)

In [ ]:
from sklearn.ensemble import HistGradientBoostingClassifier

# GBM
name = "GBM"

# Base model
model = HistGradientBoostingClassifier(
    learning_rate=0.1,
    max_depth=10,
    max_iter=5,
    random_state=42
)

# Hyperparameter tuning
param_dist = {
    'learning_rate': [0.1, 0.05],
    'max_depth': [5, 10],
    'max_iter': [100, 150]
}


# Train best model
best_model = hyper_parameter_tune(
    model,
    param_dist,
    X_train_scaled,
    y_train_sm
)

GBM = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
GBM

Best parameters: {'max_iter': 100, 'max_depth': 10, 'learning_rate': 0.1}
Best CV accuracy: 0.9987

Train Model: GBM

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,GBM,1,0.998921,0.998922,0.998921,0.998921,0.999974,0.998562,0.998561,0.998918,41.577456
1,GBM,2,0.999063,0.999064,0.999063,0.999063,0.999981,0.998752,0.998751,0.999062,42.234813
2,GBM,3,0.999043,0.999044,0.999043,0.999043,0.999878,0.998725,0.998724,0.999050,41.587615
3,GBM,4,0.997923,0.997924,0.997923,0.997923,0.999466,0.997232,0.997231,0.997931,34.277656
4,GBM,5,0.998371,0.998372,0.998371,0.998371,0.999853,0.997829,0.997828,0.998364,31.461657
5,GBM,6,0.998493,0.998494,0.998493,0.998493,0.999920,0.997992,0.997991,0.998487,34.262038
6,GBM,7,0.998127,0.998128,0.998127,0.998127,0.999531,0.997503,0.997503,0.998134,36.803792
7,GBM,8,0.998432,0.998433,0.998432,0.998432,0.999978,0.997910,0.997910,0.998421,28.777801
8,GBM,9,0.998025,0.998026,0.998025,0.998025,0.999577,0.997367,0.997367,0.998029,30.314657
9,GBM,10,0.999287,0.999288,0.999287,0.999287,0.999992,0.999050,0.999050,0.999288,37.751900

time: 23min 22s (started: 2026-05-17 00:32:36 +00:00)

time: 23min 22s (started: 2026-05-17 00:32:36 +00:00)

time: 23min 22s (started: 2026-05-17 00:32:36 +00:00)

In [ ]:
# Catboost

name ="CatBoost"

# Model
model = CatBoostClassifier(
    iterations=100,
    depth=3,
    loss_function='MultiClass',
    random_strength=1,
    verbose=0
)

param_dist = {
    'l2_leaf_reg': [1, 3, 5, 7],
    'bagging_temperature': [0, 1, 5]
}

best_model = hyper_parameter_tune(model, param_dist, X_train_scaled, y_train_sm)

CatBoost = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
CatBoost

Best parameters: {'l2_leaf_reg': 1, 'bagging_temperature': 0}
Best CV accuracy: 0.8913

Train Model: CatBoost

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,CatBoost,1,0.894214,0.895906,0.894214,0.894541,0.983491,0.859300,0.858946,0.894157,26.333577
1,CatBoost,2,0.895191,0.897635,0.895191,0.895605,0.983459,0.860811,0.860251,0.895146,26.242343
2,CatBoost,3,0.889712,0.891767,0.889712,0.890132,0.982759,0.853351,0.852941,0.889770,25.633188
3,CatBoost,4,0.894476,0.896741,0.894476,0.894926,0.982927,0.859768,0.859300,0.894578,25.184884
4,CatBoost,5,0.889957,0.891974,0.889957,0.890311,0.982554,0.853706,0.853262,0.889850,26.355227
5,CatBoost,6,0.892644,0.895010,0.892644,0.893076,0.982627,0.857376,0.856866,0.892572,26.255755
6,CatBoost,7,0.890303,0.892195,0.890303,0.890704,0.982098,0.854115,0.853746,0.890373,26.327680
7,CatBoost,8,0.891708,0.893649,0.891708,0.892103,0.982683,0.855998,0.855609,0.891615,26.428942
8,CatBoost,9,0.891239,0.893535,0.891239,0.891691,0.982765,0.855464,0.854991,0.891316,25.251043
9,CatBoost,10,0.890079,0.891985,0.890079,0.890479,0.982467,0.853813,0.853436,0.890128,25.450094

time: 14min 46s (started: 2026-05-17 00:55:59 +00:00)

In [ ]:
from sklearn.svm import SVC

# Model
model = SVC()

name="SVM"

# Param distribution
param_dist = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto'],
    'degree': [2, 3]
}

# Hyperparameter tuning
best_model = hyper_parameter_tune(
    model,
    param_dist,
    X_train_scaled,
    y_train_sm
)

SVM = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
SVM

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,SVM,1,0.999446,0.999447,0.999446,0.999446,NaN,0.999262,0.999261,0.999440,4.793383
1,SVM,2,0.999723,0.999723,0.999723,0.999723,NaN,0.999631,0.999631,0.999728,5.877714
2,SVM,3,0.999908,0.999908,0.999908,0.999908,NaN,0.999877,0.999877,0.999905,4.878195
3,SVM,4,0.999815,0.999815,0.999815,0.999815,NaN,0.999754,0.999754,0.999812,5.302073
4,SVM,5,0.999723,0.999723,0.999723,0.999723,NaN,0.999631,0.999631,0.999715,5.452982
5,SVM,6,0.999815,0.999815,0.999815,0.999815,NaN,0.999754,0.999754,0.999813,5.040118
6,SVM,7,0.999723,0.999723,0.999723,0.999723,NaN,0.999631,0.999631,0.999728,6.137564
7,SVM,8,0.999723,0.999723,0.999723,0.999723,NaN,0.999631,0.999631,0.999723,4.628765
8,SVM,9,0.999723,0.999723,0.999723,0.999723,NaN,0.999631,0.999631,0.999728,5.988212
9,SVM,10,0.999631,0.999631,0.999631,0.999631,NaN,0.999508,0.999508,0.999644,4.787380

time: 50.8 ms (started: 2026-05-19 08:40:21 +00:00)

In [ ]:
from sklearn.linear_model import LogisticRegression

name ="Logistic Regression" # change as per model

# Model
model = LogisticRegression(random_state=42, max_iter=1000, solver="liblinear", C = 1.0) # change as per model

# Parameters, change as per model
param_dist = {
        'C': [0.1, 0.6, 0.8, 1],
        'penalty': ['l2'],
        'solver': ['lbfgs', 'liblinear']
}

best_model = hyper_parameter_tune(model, param_dist, X_train_scaled, y_train_sm)

Logistic_Regression = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
Logistic_Regression

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,Logistic Regression,1,0.951068,0.951375,0.951068,0.951142,0.994168,0.934807,0.934756,0.951076,34.057681
1,Logistic Regression,2,0.950544,0.950841,0.950544,0.950609,0.993956,0.934112,0.934057,0.950460,33.639572
2,Logistic Regression,3,0.952219,0.952552,0.952219,0.952278,0.994325,0.936363,0.936293,0.952324,35.779835
3,Logistic Regression,4,0.949027,0.949364,0.949027,0.949126,0.994382,0.932078,0.932032,0.949005,32.728733
4,Logistic Regression,5,0.953056,0.953313,0.953056,0.953103,0.993910,0.937456,0.937403,0.953084,31.209545
5,Logistic Regression,6,0.951225,0.951545,0.951225,0.951303,0.994150,0.935006,0.934955,0.951198,35.570221
6,Logistic Regression,7,0.949129,0.949394,0.949129,0.949185,0.994228,0.932222,0.932173,0.949137,30.048933
7,Logistic Regression,8,0.948553,0.948947,0.948553,0.948650,0.993576,0.931460,0.931395,0.948537,32.932031
8,Logistic Regression,9,0.949914,0.950097,0.949914,0.949964,0.994150,0.933242,0.933215,0.949831,33.075392
9,Logistic Regression,10,0.950228,0.950519,0.950228,0.950308,0.994160,0.933679,0.933637,0.950284,34.923320

time: 36.3 ms (started: 2026-05-19 08:40:39 +00:00)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

name = "Random Forest"

# Model
model = RandomForestClassifier(n_jobs=-1,
    random_state=42
)

# Parameters
param_dist = {
    'n_estimators': [50, 100],
    'max_depth': [5, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

best_model = hyper_parameter_tune(model, param_dist, X_train_scaled, y_train_sm)

Random_Forest = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
Random_Forest

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,Random Forest,1,0.988558,0.988653,0.988558,0.988562,0.999690,0.984773,0.984744,0.988541,240.456005
1,Random Forest,2,0.988192,0.988303,0.988192,0.988200,0.999683,0.984287,0.984256,0.988184,239.989493
2,Random Forest,3,0.988029,0.988139,0.988029,0.988038,0.999688,0.984068,0.984038,0.988014,237.088522
3,Random Forest,4,0.987662,0.987751,0.987662,0.987667,0.999691,0.983576,0.983549,0.987669,237.929663
4,Random Forest,5,0.986726,0.986859,0.986726,0.986735,0.999644,0.982338,0.982300,0.986686,241.613954
5,Random Forest,6,0.987255,0.987360,0.987255,0.987262,0.999629,0.983037,0.983007,0.987257,243.219578
6,Random Forest,7,0.987621,0.987739,0.987621,0.987631,0.999607,0.983528,0.983495,0.987645,240.266899
7,Random Forest,8,0.987540,0.987664,0.987540,0.987547,0.999623,0.983423,0.983386,0.987559,240.423835
8,Random Forest,9,0.987886,0.988016,0.987886,0.987896,0.999692,0.983885,0.983848,0.987904,237.978543
9,Random Forest,10,0.988354,0.988460,0.988354,0.988361,0.999706,0.984503,0.984472,0.988361,240.936251

time: 37.4 ms (started: 2026-05-19 08:40:50 +00:00)

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

name="BaggingClassifier"

model = BaggingClassifier(
    estimator=my_base_model,
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)
param_dist = {
    "n_estimators": [100],
    "max_samples": [0.75, 1.0],
    "max_features": [0.75, 1.0]
}

best_model = hyper_parameter_tune(model, param_dist, X_train_sm, y_train_sm)

Bagging = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
Bagging

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,BaggingClassifier,1,0.899446,0.900222,0.899446,0.899409,0.985994,0.866206,0.865922,0.899375,99.692653
1,BaggingClassifier,2,0.902541,0.903420,0.902541,0.902607,0.986109,0.870304,0.870051,0.902493,98.290943
2,BaggingClassifier,3,0.902417,0.903125,0.902417,0.902430,0.986282,0.870118,0.869888,0.902534,100.168385
3,BaggingClassifier,4,0.902233,0.903120,0.902233,0.902245,0.985781,0.869940,0.869648,0.902387,101.923950
4,BaggingClassifier,5,0.901480,0.902305,0.901480,0.901499,0.985697,0.868896,0.868628,0.901351,98.396888
5,BaggingClassifier,6,0.898243,0.899349,0.898243,0.898327,0.985343,0.864638,0.864321,0.898060,96.950112
6,BaggingClassifier,7,0.900930,0.901797,0.900930,0.900949,0.985696,0.868193,0.867915,0.901010,99.043154
7,BaggingClassifier,8,0.902905,0.903585,0.902905,0.902913,0.985959,0.870755,0.870532,0.902759,105.153057
8,BaggingClassifier,9,0.900035,0.900972,0.900035,0.900101,0.985556,0.866991,0.866719,0.900147,108.048750
9,BaggingClassifier,10,0.901399,0.902180,0.901399,0.901496,0.985789,0.868730,0.868532,0.901472,108.764375

time: 35.4 ms (started: 2026-05-19 08:41:02 +00:00)

In [ ]:
from lightgbm import LGBMClassifier

name = "LightGBM" # change as per model

# Model
model = LGBMClassifier(n_jobs=2, verbose=-1) # change as per model

# Parameters, change as per model
param_dist = {
        'n_estimators': [21, 51, 101],
        'learning_rate': [0.01, 0.05, 0.08],
        'num_leaves': [30, 50, 70],
        'max_depth': [-1, 5, 10],
        'subsample': [0.2, 0.5, 0.8],
        'colsample_bytree': [0.2, 0.5, 0.8]
    }

best_model = hyper_parameter_tune(model, param_dist, X_train_scaled, y_train_sm)
LightGBM = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
LightGBM

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,LightGBM,1,0.995847,0.995848,0.995847,0.995845,0.999934,0.994464,0.994462,0.995838,56.014437
1,LightGBM,2,0.996274,0.996275,0.996274,0.996273,0.999951,0.995034,0.995032,0.996269,24.201820
2,LightGBM,3,0.995724,0.995727,0.995724,0.995723,0.999945,0.994301,0.994299,0.995733,24.415209
3,LightGBM,4,0.995887,0.995889,0.995887,0.995886,0.999926,0.994518,0.994516,0.995897,27.952126
4,LightGBM,5,0.995684,0.995685,0.995684,0.995682,0.999934,0.994246,0.994245,0.995669,24.246713
5,LightGBM,6,0.995602,0.995603,0.995602,0.995600,0.999934,0.994138,0.994136,0.995595,25.331151
6,LightGBM,7,0.995582,0.995586,0.995582,0.995581,0.999938,0.994112,0.994109,0.995596,20.548093
7,LightGBM,8,0.995928,0.995931,0.995928,0.995927,0.999944,0.994572,0.994571,0.995913,21.111623
8,LightGBM,9,0.996356,0.996360,0.996356,0.996355,0.999956,0.995143,0.995141,0.996363,24.533791
9,LightGBM,10,0.996274,0.996276,0.996274,0.996273,0.999961,0.995034,0.995032,0.996275,23.833752

time: 37.1 ms (started: 2026-05-19 08:41:12 +00:00)

In [ ]:
name="KNN"

from sklearn.neighbors import KNeighborsClassifier

# Model
model = KNeighborsClassifier(n_jobs=-1);

# Param distribution
param_dist = {
    'n_neighbors': [3, 5, 7],     # keep small range
    'weights': ['uniform'],          # distance = slower
    'p': [2],                        # Euclidean only (faster)
    'algorithm': ['kd_tree']         # fastest in most cases
}

# Hyperparameter tuning
best_model = hyper_parameter_tune(
    model,
    param_dist,
    X_train_scaled,
    y_train_sm
)

KNN = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
KNN

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,KNN,1,0.998880,0.998882,0.998880,0.998880,0.999595,0.998508,0.998507,0.998876,5.776723
1,KNN,2,0.998921,0.998923,0.998921,0.998920,0.999592,0.998562,0.998561,0.998918,4.726142
2,KNN,3,0.998534,0.998537,0.998534,0.998533,0.999504,0.998047,0.998045,0.998547,5.922305
3,KNN,4,0.998819,0.998821,0.998819,0.998819,0.999558,0.998426,0.998426,0.998829,4.767427
4,KNN,5,0.998758,0.998760,0.998758,0.998757,0.999482,0.998345,0.998344,0.998751,4.947465
5,KNN,6,0.998758,0.998760,0.998758,0.998757,0.999453,0.998345,0.998344,0.998747,6.049948
6,KNN,7,0.998697,0.998699,0.998697,0.998696,0.999557,0.998264,0.998263,0.998703,4.816549
7,KNN,8,0.999125,0.999125,0.999125,0.999124,0.999726,0.998833,0.998833,0.999116,4.885449
8,KNN,9,0.999002,0.999004,0.999002,0.999002,0.999649,0.998670,0.998670,0.999008,4.726678
9,KNN,10,0.998962,0.998963,0.998962,0.998961,0.999651,0.998616,0.998616,0.998965,4.725839

time: 54 ms (started: 2026-05-19 08:41:20 +00:00)

In [ ]:
name = "StackingClassifier"

from sklearn.ensemble import StackingClassifier
#Model
model = StackingClassifier(
          cv=3,
        estimators=[
            ('lr', LogisticRegression(random_state=42)),
            ('dt', DecisionTreeClassifier(random_state=42, max_depth=2)),
        ],
        n_jobs=-1,
        verbose=0,
         )
param_dist = {
       'passthrough': [False],
        'final_estimator': [LogisticRegression(random_state=42, max_iter=100)]
}

# Hyperparameter tuning
best_model = hyper_parameter_tune(
    model,
    param_dist,
    X_train_scaled,
    y_train_sm
)

Stacking = evaluate_models(name, best_model, X_train_scaled, y_train_sm)
Stacking

,Classifier,Fold,Accuracy,Precision,Recall,F1,AUC,MCC,Kappa,Balanced Accuracy,Training Time (s)
0,StackingClassifier,1,0.929496,0.929710,0.929496,0.929570,0.989126,0.906017,0.905995,0.929509,40.924548
1,StackingClassifier,2,0.927929,0.928343,0.927929,0.928033,0.989482,0.903972,0.903905,0.927937,43.022943
2,StackingClassifier,3,0.932386,0.932586,0.932386,0.932444,0.989974,0.909871,0.909844,0.932402,42.043369
3,StackingClassifier,4,0.927663,0.927886,0.927663,0.927733,0.989463,0.903575,0.903548,0.927684,40.745109
4,StackingClassifier,5,0.927479,0.927811,0.927479,0.927574,0.988757,0.903350,0.903303,0.927501,40.738126
5,StackingClassifier,6,0.929821,0.930178,0.929821,0.929926,0.988898,0.906477,0.906429,0.929814,41.119242
6,StackingClassifier,7,0.927174,0.927539,0.927174,0.927290,0.989001,0.902941,0.902898,0.927156,41.049913
7,StackingClassifier,8,0.929780,0.930177,0.929780,0.929893,0.989299,0.906428,0.906372,0.929743,40.947556
8,StackingClassifier,9,0.927398,0.927639,0.927398,0.927468,0.989101,0.903229,0.903196,0.927375,41.322491
9,StackingClassifier,10,0.929637,0.929880,0.929637,0.929692,0.989556,0.906224,0.906180,0.929608,40.824412

time: 66.7 ms (started: 2026-05-19 08:41:31 +00:00)

In [ ]:
import pandas as pd

# Create one Excel file with separate sheets
with pd.ExcelWriter('/content/all_models.xlsx') as writer:

    CatBoost.to_excel(writer, sheet_name='CatBoost', index=False)

    Logistic_Regression.to_excel(writer, sheet_name='Logistic_Regression', index=False)

    GBM.to_excel(writer, sheet_name='GBM', index=False)

    MLP.to_excel(writer, sheet_name='MLP', index=False)

    XGBoost.to_excel(writer, sheet_name='XGBoost', index=False)

    DecisionTree.to_excel(writer, sheet_name='DecisionTree', index=False)

    Random_Forest.to_excel(writer, sheet_name='Random_Forest', index=False)

    KNN.to_excel(writer, sheet_name='KNN', index=False)

    Bagging.to_excel(writer, sheet_name='Bagging', index=False)

    Stacking.to_excel(writer, sheet_name='Stacking', index=False)

    LightGBM.to_excel(writer, sheet_name='LightGBM', index=False)

    SVM.to_excel(writer, sheet_name='SVM', index=False)

print("All DataFrames saved into one Excel file with separate sheets!")

All DataFrames saved into one Excel file with separate sheets!
time: 51 ms (started: 2026-05-19 08:29:05 +00:00)

In [ ]:
!pip install matplotlib-venn
!apt-get -qq install -y libfluidsynth1

# https://pypi.python.org/pypi/libarchive
# !apt-get -qq install -y libarchive-dev && pip install -U libarchive
# import libarchive

# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

!pip install cartopy
import cartopy

Requirement already satisfied: matplotlib-venn in /usr/local/lib/python3.12/dist-packages (1.1.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from matplotlib-venn) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from matplotlib-venn) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from matplotlib-venn) (1.16.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->matplotlib-venn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->matplotlib-venn) (1.17.0)
E: Package 'libfluidsynth1' has no installation candidate
Requirement already satisfied: pydot in /usr/local/lib/python3.12/dist-packages (4.0.1)
Requirement already satisfied: pyparsing>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from pydot) (3.3.2)
Collecting cartopy
  Downloading cartopy-0.25.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from cartopy) (2.0.2)
Requirement already satisfied: matplotlib>=3.6 in /usr/local/lib/python3.12/dist-packages (from cartopy) (3.10.0)
Requirement already satisfied: shapely>=2.0 in /usr/local/lib/python3.12/dist-packages (from cartopy) (2.1.2)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from cartopy) (26.1)
Requirement already satisfied: pyshp>=2.3 in /usr/local/lib/python3.12/dist-packages (from cartopy) (3.0.3)
Requirement already satisfied: pyproj>=3.3.1 in /usr/local/lib/python3.12/dist-packages (from cartopy) (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.6->cartopy) (2.9.0.post0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyproj>=3.3.1->cartopy) (2026.4.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6->cartopy) (1.17.0)
Downloading cartopy-0.25.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 117.4 MB/s eta 0:00:00
Installing collected packages: cartopy
Successfully installed cartopy-0.25.0
time: 21.7 s (started: 2026-05-19 08:32:45 +00:00)

In [ ]:
import glob
import os

!pip install xlsxwriter

folder_path = "/content/drive/MyDrive/"
csv_files = sorted(glob.glob(os.path.join(folder_path, "*.csv")))
# csv_files.remove('/content/bank-additional-full.csv')
metrics = [
    "Accuracy", "Precision", "Recall",
    "F1", "AUC", "MCC", "Kappa",
    "Balanced Accuracy"
]

metric_tables = {metric: pd.DataFrame() for metric in metrics}

for file in csv_files:
    df = pd.read_csv(file)

    name = df.get("Classifier").iloc[0]
    # name = os.path.splitext(os.path.basename(file))[0]
    for metric in metrics:
        temp = df[["Fold", metric]].copy()
        temp = temp.set_index("Fold")
        metric_tables[metric][name] = temp[metric]

output_file = "all_model.xlsx"

with pd.ExcelWriter(output_file, engine="xlsxwriter") as writer:
    for metric, table in metric_tables.items():
        table = table.sort_index()
        sheet_name = metric[:31]
        table.to_excel(writer, sheet_name=sheet_name)

print("Excel file created:", output_file)

Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.12/dist-packages (3.2.9)
Excel file created: all_model.xlsx
time: 4.29 s (started: 2026-05-19 08:36:30 +00:00)

In [ ]:
# wilcoxon
import pandas as pd
from scipy.stats import wilcoxon
import itertools

file_path = "all_models.xlsx"

xls = pd.ExcelFile(file_path)
sheets = xls.sheet_names

results = []

for sheet in sheets:
    df = pd.read_excel(file_path, sheet_name=sheet)

    df = df.set_index(df.columns[0])
    models = df.columns

    for model1, model2 in itertools.combinations(models, 2):
        x = df[model1]
        y = df[model2]


        stat, p = wilcoxon(x, y, nan_policy='omit')

        results.append({
            "Metric": sheet,
            "Reference Model": model1,
            "Compared Model": model2,
            "Wilcoxon Statistic": stat,
            "p-value": p,
            "Significant (p < 0.05)": p < 0.05
        })

# Convert to DataFrame
results_df = pd.DataFrame(results)

# Save
output_file = "Wilcoxon_Signed_Rank_Test_results.xlsx"
results_df.to_excel(output_file, index=False)

print("Saved :", output_file)
results_df

/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se
/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1006: SmallSampleWarning: After omitting NaNs, one or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  return fun(*args, **kwargs)
/usr/local/lib/python3.12/dist-packages/scipy/stats/_wilcoxon.py:178: RuntimeWarning: invalid value encountered in scalar divide
  z = (r_plus - mn) / se

Saved : Wilcoxon_Signed_Rank_Test_results.xlsx

,Metric,Reference Model,Compared Model,Wilcoxon Statistic,p-value,Significant (p < 0.05)
0,CatBoost,Fold,Accuracy,0.0,0.001953,True
1,CatBoost,Fold,Precision,0.0,0.001953,True
2,CatBoost,Fold,Recall,0.0,0.001953,True
3,CatBoost,Fold,F1,0.0,0.001953,True
4,CatBoost,Fold,AUC,0.0,0.001953,True
...,...,...,...,...,...,...
535,SVM,MCC,Balanced Accuracy,0.0,0.001953,True
536,SVM,MCC,Training Time (s),0.0,0.001953,True
537,SVM,Kappa,Balanced Accuracy,0.0,0.001953,True
538,SVM,Kappa,Training Time (s),0.0,0.001953,True
539,SVM,Balanced Accuracy,Training Time (s),0.0,0.001953,True

time: 52.6 s (started: 2026-05-19 08:36:43 +00:00)

In [ ]:
results_df.to_csv("Wilcoxon_Signed_Rank_Test_results.csv", index=False)

from google.colab import files
files.download("Wilcoxon_Signed_Rank_Test_results.csv")

time: 60.3 ms (started: 2026-05-19 08:39:36 +00:00)